version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin          # same as SPRING_DATASOURCE_PASSWORD
      MYSQL_DATABASE: testdb              # same as in SPRING_DATASOURCE_URL
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  backend:
    # Option 1: build image from your Dockerfile locally
    build: .
    image: sairamk5/my-userapp              # same image name you use in k8s & Jenkins
    container_name: backend
    restart: always
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/testdb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: admin
    ports:
      - "8081:8080"

volumes:
  mysql-data:

